"""
ISO 3166-1 alpha-2 country code → {name, language} mapping.
Used by researcher.py to resolve two-letter codes to display names.
"""

COUNTRIES: dict[str, dict[str, str]] = {
    "AF": {"name": "Afghanistan", "lang": "fa"},
    "AL": {"name": "Albania", "lang": "sq"},
    "DZ": {"name": "Algeria", "lang": "ar"},
    "AD": {"name": "Andorra", "lang": "ca"},
    "AO": {"name": "Angola", "lang": "pt"},
    "AG": {"name": "Antigua and Barbuda", "lang": "en"},
    "AR": {"name": "Argentina", "lang": "es"},
    "AM": {"name": "Armenia", "lang": "hy"},
    "AU": {"name": "Australia", "lang": "en"},
    "AT": {"name": "Austria", "lang": "de"},
    "AZ": {"name": "Azerbaijan", "lang": "az"},
    "BS": {"name": "Bahamas", "lang": "en"},
    "BH": {"name": "Bahrain", "lang": "ar"},
    "BD": {"name": "Bangladesh", "lang": "bn"},
    "BB": {"name": "Barbados", "lang": "en"},
    "BY": {"name": "Belarus", "lang": "be"},
    "BE": {"name": "Belgium", "lang": "nl"},
    "BZ": {"name": "Belize", "lang": "en"},
    "BJ": {"name": "Benin", "lang": "fr"},
    "BT": {"name": "Bhutan", "lang": "dz"},
    "BO": {"name": "Bolivia", "lang": "es"},
    "BA": {"name": "Bosnia and Herzegovina", "lang": "bs"},
    "BW": {"name": "Botswana", "lang": "en"},
    "BR": {"name": "Brazil", "lang": "pt"},
    "BN": {"name": "Brunei", "lang": "ms"},
    "BG": {"name": "Bulgaria", "lang": "bg"},
    "BF": {"name": "Burkina Faso", "lang": "fr"},
    "BI": {"name": "Burundi", "lang": "fr"},
    "CV": {"name": "Cabo Verde", "lang": "pt"},
    "KH": {"name": "Cambodia", "lang": "km"},
    "CM": {"name": "Cameroon", "lang": "fr"},
    "CA": {"name": "Canada", "lang": "en"},
    "CF": {"name": "Central African Republic", "lang": "fr"},
    "TD": {"name": "Chad", "lang": "fr"},
    "CL": {"name": "Chile", "lang": "es"},
    "CN": {"name": "China", "lang": "zh"},
    "CO": {"name": "Colombia", "lang": "es"},
    "KM": {"name": "Comoros", "lang": "ar"},
    "CD": {"name": "Congo (DRC)", "lang": "fr"},
    "CG": {"name": "Congo (Republic)", "lang": "fr"},
    "CR": {"name": "Costa Rica", "lang": "es"},
    "HR": {"name": "Croatia", "lang": "hr"},
    "CU": {"name": "Cuba", "lang": "es"},
    "CY": {"name": "Cyprus", "lang": "el"},
    "CZ": {"name": "Czechia", "lang": "cs"},
    "DK": {"name": "Denmark", "lang": "da"},
    "DJ": {"name": "Djibouti", "lang": "fr"},
    "DM": {"name": "Dominica", "lang": "en"},
    "DO": {"name": "Dominican Republic", "lang": "es"},
    "EC": {"name": "Ecuador", "lang": "es"},
    "EG": {"name": "Egypt", "lang": "ar"},
    "SV": {"name": "El Salvador", "lang": "es"},
    "GQ": {"name": "Equatorial Guinea", "lang": "es"},
    "ER": {"name": "Eritrea", "lang": "ti"},
    "EE": {"name": "Estonia", "lang": "et"},
    "SZ": {"name": "Eswatini", "lang": "en"},
    "ET": {"name": "Ethiopia", "lang": "am"},
    "FJ": {"name": "Fiji", "lang": "en"},
    "FI": {"name": "Finland", "lang": "fi"},
    "FR": {"name": "France", "lang": "fr"},
    "GA": {"name": "Gabon", "lang": "fr"},
    "GM": {"name": "Gambia", "lang": "en"},
    "GE": {"name": "Georgia", "lang": "ka"},
    "DE": {"name": "Germany", "lang": "de"},
    "GH": {"name": "Ghana", "lang": "en"},
    "GR": {"name": "Greece", "lang": "el"},
    "GD": {"name": "Grenada", "lang": "en"},
    "GT": {"name": "Guatemala", "lang": "es"},
    "GN": {"name": "Guinea", "lang": "fr"},
    "GW": {"name": "Guinea-Bissau", "lang": "pt"},
    "GY": {"name": "Guyana", "lang": "en"},
    "HT": {"name": "Haiti", "lang": "fr"},
    "HN": {"name": "Honduras", "lang": "es"},
    "HU": {"name": "Hungary", "lang": "hu"},
    "IS": {"name": "Iceland", "lang": "is"},
    "IN": {"name": "India", "lang": "hi"},
    "ID": {"name": "Indonesia", "lang": "id"},
    "IR": {"name": "Iran", "lang": "fa"},
    "IQ": {"name": "Iraq", "lang": "ar"},
    "IE": {"name": "Ireland", "lang": "en"},
    "IL": {"name": "Israel", "lang": "he"},
    "IT": {"name": "Italy", "lang": "it"},
    "JM": {"name": "Jamaica", "lang": "en"},
    "JP": {"name": "Japan", "lang": "ja"},
    "JO": {"name": "Jordan", "lang": "ar"},
    "KZ": {"name": "Kazakhstan", "lang": "kk"},
    "KE": {"name": "Kenya", "lang": "sw"},
    "KI": {"name": "Kiribati", "lang": "en"},
    "KP": {"name": "North Korea", "lang": "ko"},
    "KR": {"name": "South Korea", "lang": "ko"},
    "KW": {"name": "Kuwait", "lang": "ar"},
    "KG": {"name": "Kyrgyzstan", "lang": "ky"},
    "LA": {"name": "Laos", "lang": "lo"},
    "LV": {"name": "Latvia", "lang": "lv"},
    "LB": {"name": "Lebanon", "lang": "ar"},
    "LS": {"name": "Lesotho", "lang": "en"},
    "LR": {"name": "Liberia", "lang": "en"},
    "LY": {"name": "Libya", "lang": "ar"},
    "LI": {"name": "Liechtenstein", "lang": "de"},
    "LT": {"name": "Lithuania", "lang": "lt"},
    "LU": {"name": "Luxembourg", "lang": "lb"},
    "MG": {"name": "Madagascar", "lang": "mg"},
    "MW": {"name": "Malawi", "lang": "en"},
    "MY": {"name": "Malaysia", "lang": "ms"},
    "MV": {"name": "Maldives", "lang": "dv"},
    "ML": {"name": "Mali", "lang": "fr"},
    "MT": {"name": "Malta", "lang": "mt"},
    "MH": {"name": "Marshall Islands", "lang": "en"},
    "MR": {"name": "Mauritania", "lang": "ar"},
    "MU": {"name": "Mauritius", "lang": "en"},
    "MX": {"name": "Mexico", "lang": "es"},
    "FM": {"name": "Micronesia", "lang": "en"},
    "MD": {"name": "Moldova", "lang": "ro"},
    "MC": {"name": "Monaco", "lang": "fr"},
    "MN": {"name": "Mongolia", "lang": "mn"},
    "ME": {"name": "Montenegro", "lang": "sr"},
    "MA": {"name": "Morocco", "lang": "ar"},
    "MZ": {"name": "Mozambique", "lang": "pt"},
    "MM": {"name": "Myanmar", "lang": "my"},
    "NA": {"name": "Namibia", "lang": "en"},
    "NR": {"name": "Nauru", "lang": "en"},
    "NP": {"name": "Nepal", "lang": "ne"},
    "NL": {"name": "Netherlands", "lang": "nl"},
    "NZ": {"name": "New Zealand", "lang": "en"},
    "NI": {"name": "Nicaragua", "lang": "es"},
    "NE": {"name": "Niger", "lang": "fr"},
    "NG": {"name": "Nigeria", "lang": "en"},
    "NO": {"name": "Norway", "lang": "no"},
    "OM": {"name": "Oman", "lang": "ar"},
    "PK": {"name": "Pakistan", "lang": "ur"},
    "PW": {"name": "Palau", "lang": "en"},
    "PA": {"name": "Panama", "lang": "es"},
    "PG": {"name": "Papua New Guinea", "lang": "en"},
    "PY": {"name": "Paraguay", "lang": "es"},
    "PE": {"name": "Peru", "lang": "es"},
    "PH": {"name": "Philippines", "lang": "fil"},
    "PL": {"name": "Poland", "lang": "pl"},
    "PT": {"name": "Portugal", "lang": "pt"},
    "QA": {"name": "Qatar", "lang": "ar"},
    "RO": {"name": "Romania", "lang": "ro"},
    "RU": {"name": "Russia", "lang": "ru"},
    "RW": {"name": "Rwanda", "lang": "rw"},
    "KN": {"name": "Saint Kitts and Nevis", "lang": "en"},
    "LC": {"name": "Saint Lucia", "lang": "en"},
    "VC": {"name": "Saint Vincent and the Grenadines", "lang": "en"},
    "WS": {"name": "Samoa", "lang": "sm"},
    "SM": {"name": "San Marino", "lang": "it"},
    "ST": {"name": "São Tomé and Príncipe", "lang": "pt"},
    "SA": {"name": "Saudi Arabia", "lang": "ar"},
    "SN": {"name": "Senegal", "lang": "fr"},
    "RS": {"name": "Serbia", "lang": "sr"},
    "SC": {"name": "Seychelles", "lang": "fr"},
    "SL": {"name": "Sierra Leone", "lang": "en"},
    "SG": {"name": "Singapore", "lang": "en"},
    "SK": {"name": "Slovakia", "lang": "sk"},
    "SI": {"name": "Slovenia", "lang": "sl"},
    "SB": {"name": "Solomon Islands", "lang": "en"},
    "SO": {"name": "Somalia", "lang": "so"},
    "ZA": {"name": "South Africa", "lang": "en"},
    "SS": {"name": "South Sudan", "lang": "en"},
    "ES": {"name": "Spain", "lang": "es"},
    "LK": {"name": "Sri Lanka", "lang": "si"},
    "SD": {"name": "Sudan", "lang": "ar"},
    "SR": {"name": "Suriname", "lang": "nl"},
    "SE": {"name": "Sweden", "lang": "sv"},
    "CH": {"name": "Switzerland", "lang": "de"},
    "SY": {"name": "Syria", "lang": "ar"},
    "TW": {"name": "Taiwan", "lang": "zh"},
    "TJ": {"name": "Tajikistan", "lang": "tg"},
    "TZ": {"name": "Tanzania", "lang": "sw"},
    "TH": {"name": "Thailand", "lang": "th"},
    "TL": {"name": "Timor-Leste", "lang": "pt"},
    "TG": {"name": "Togo", "lang": "fr"},
    "TO": {"name": "Tonga", "lang": "to"},
    "TT": {"name": "Trinidad and Tobago", "lang": "en"},
    "TN": {"name": "Tunisia", "lang": "ar"},
    "TR": {"name": "Turkey", "lang": "tr"},
    "TM": {"name": "Turkmenistan", "lang": "tk"},
    "TV": {"name": "Tuvalu", "lang": "en"},
    "UG": {"name": "Uganda", "lang": "en"},
    "UA": {"name": "Ukraine", "lang": "uk"},
    "AE": {"name": "United Arab Emirates", "lang": "ar"},
    "GB": {"name": "United Kingdom", "lang": "en"},
    "US": {"name": "United States", "lang": "en"},
    "UY": {"name": "Uruguay", "lang": "es"},
    "UZ": {"name": "Uzbekistan", "lang": "uz"},
    "VU": {"name": "Vanuatu", "lang": "bi"},
    "VE": {"name": "Venezuela", "lang": "es"},
    "VN": {"name": "Vietnam", "lang": "vi"},
    "YE": {"name": "Yemen", "lang": "ar"},
    "ZM": {"name": "Zambia", "lang": "en"},
    "ZW": {"name": "Zimbabwe", "lang": "en"},
}


def code_to_name(code: str) -> str | None:
    """Return the country name for an ISO-3166-1 alpha-2 code, or None."""
    return COUNTRIES.get(code.upper(), {}).get("name")


def code_to_lang(code: str) -> str | None:
    """Return the primary language BCP-47 tag for a country code, or None."""
    return COUNTRIES.get(code.upper(), {}).get("lang")
